POST http://localhost:3000/users 
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@user.com",
    "password": "admin",
    "role": "ADMIN"
}

###

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQHVzZXIuY29tIiwicm9sZSI6IkFETUlOIiwic3ViIjoiY21hMDV6cWo3MDAwMGMzZnJvMzQ0OWVrcCIsImlhdCI6MTc0NTc5MjkxMCwiZXhwIjoxNzQ1ODAwMTEwfQ.qw_rEtp9D42aWsfK3EcwQWMG9S6mwtkEQDzVrUHMmI0
###

GET http://localhost:3000/users/cma05zqj70000c3fro3449ekp

###

DELETE http://localhost:3000/users/

###

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin"
}