POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@user.com",
    "password": "admin",
    "role": "ADMIN"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/cm9r7jlon0006c3ywnszr4nv3


###
DELETE  http://localhost:3000/users/cm9yrthor0000u4ahxuyrvk0q